#!/usr/bin/env python3
# Generate a proper favicon for DreamOS
import base64
import os

# This is a base64-encoded simple blue icon
icon_data = """
AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSkv/TEpL/0xKS/9MSkv/TEpL/0xKS/9MSkv/TEpL
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExKS/9MSkv/TEpL/0xKS/9MSkv/TEpL/0xKS/9MSkv/
TEpL/0xKS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSkv/TEpL/0xKS/9MSkv/TEpL/0xKS/9M
Skv/TEpL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExKS/9MSkv/TEpL/0xKS/9MSkv/TEpL/0xK
S/9MSkv/TEpL/0xKS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSkv/TEpL/0xKS/9MSkv/TEpL
/0xKS/9MSkv/TEpL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExKS/9MSkv/TEpL/0xKS/9MSkv/
TEpL/0xKS/9MSkv/TEpL/0xKS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSkv/TEpL/0xKS/9M
Skv/TEpL/0xKS/9MSkv/TEpL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExKS/9MSkv/TEpL/0xK
S/9MSkv/TEpL/0xKS/9MSkv/TEpL/0xKS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSkv/TEpL
/0xKS/9MSkv/TEpL/0xKS/9MSkv/TEpL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExKS/9MSkv/
TEpL/0xKS/9MSkv/TEpL/0xKS/9MSkv/TEpL/0xKS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABM
Skv/TEpL/0xKS/9MSkv/TEpL/0xKS/9MSkv/TEpL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgPwAAwB8A
AMAHAADAAwAAwAMAAMADAADAAwAAwAMAAMADAADAAwAAwAMAAMADAADABwAAwB8AAOAfAADwPwAA
"""

# Remove newlines and decode
clean_data = icon_data.strip()
binary_data = base64.b64decode(clean_data)

# Write to the file
with open('dreamos/web/static/img/favicon.ico', 'wb') as f:
    f.write(binary_data)

print("Fixed favicon created successfully!") 